### ISSUE TITLE
Minimize the number of config settings needed to get started

### ISSUE THREAD

**Issue by joeriddles** [joeriddles/goalesce#2]
Slim this down:

```yaml
# ./config.yaml
input_folder_path: ./model
output_file_path: ./generated
module_name: github.com/joeriddles/goalesce/examples/basic
models_package: github.com/joeriddles/goalesce/examples/basic/model
query_package: github.com/joeriddles/goalesce/examples/basic/query
clear_output_dir: true
```
